# Generated by Django 4.1.2 on 2022-12-06 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciezarowka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaCiezarowki', models.CharField(max_length=60, null=True)),
                ('nazwaMarki', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaZlecenia', models.CharField(max_length=60)),
                ('nazwaLadunku', models.IntegerField(choices=[(1, 'Explosives'), (2, 'Gases'), (3, 'Flammableliquids'), (4, 'Flammablesolids'), (5, 'Toxic'), (6, 'Corrosivesubstances')], default=1)),
                ('dystans', models.CharField(max_length=60)),
                ('czasRealizacji', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kierowca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('kryteriumLadunek', models.IntegerField(choices=[(1, 'Explosives'), (2, 'Gases'), (3, 'Flammableliquids'), (4, 'Flammablesolids'), (5, 'Toxic'), (6, 'Corrosivesubstances')], default=(1, 'Explosives'))),
                ('kryteriumDystans', models.IntegerField(choices=[(350, 'Do 350'), (550, 'Do 550'), (850, 'Do 850'), (1100, 'Do 1100'), (1500, 'Do 1500'), (1, 'Wszedzie')], default=(350, 'Do 350'))),
                ('data_dodania', models.DateField(auto_now_add=True)),
                ('ciezarowka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naszaAplikacja.ciezarowka')),
                ('zlecenia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naszaAplikacja.zlecenia')),
            ],
            options={
                'ordering': ['nazwisko'],
            },
        ),
    ]
