# Generated by Django 4.1.2 on 2022-12-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naszaAplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciezarowka',
            name='nazwaMarki',
            field=models.IntegerField(choices=[(1, 'Volvo'), (2, 'Scania'), (3, 'Daf'), (4, 'Iveco'), (5, 'Man'), (6, 'Mercedes'), (7, 'Renault')], default=1),
        ),
    ]
