# Generated by Django 4.1.2 on 2022-12-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naszaAplikacja', '0003_remove_kierowca_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kierowca',
            name='kryteriumLadunek',
            field=models.IntegerField(choices=[(1, 'Explosives'), (2, 'Gases'), (3, 'Flammableliquids'), (4, 'Flammablesolids'), (5, 'Toxic'), (6, 'Corrosivesubstances')]),
        ),
    ]
