# Generated by Django 4.1.2 on 2022-12-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naszaAplikacja', '0005_alter_kierowca_kryteriumdystans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kierowca',
            name='kryteriumDystans',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='zlecenia',
            name='dystans',
            field=models.IntegerField(max_length=60),
        ),
    ]
